# Generated by Django 4.2.7 on 2026-05-14 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='tickets.ticket')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
