# Generated by Django 4.2.7 on 2026-05-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('draw_date', models.DateField()),
                ('is_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('num4', models.IntegerField()),
                ('num5', models.IntegerField()),
                ('num6', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('draw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='draws.draw')),
            ],
        ),
    ]
